### ISSUE TITLE
The wrong of extrinsics

### ISSUE THREAD

**Issue by qianmingduowan** [nickponline/dd-nerf-dataset#1]
Hi,
I find that when I use instant-ngp to render the scene, the result is not well as the https://raw.githubusercontent.com/nickponline/dd-nerf-dataset/main/imgs/ngp.png 
So I tried to render the dataset in nerf, but find the same question, the rendered image is blur.
I think the probable reason is that the extrinsics is not right.
Can you re-upload the correct dataset? or show me the quantitative result rendered with instant-ngp like PSNR?

**Comment by nickponline** [comment]
The PSNR is on the right of the image you shared. `22.44dB` after `13264` steps. 

If you can share the steps to reproduce I can possible help you out?

**Comment by nickponline** [comment]
Under debug visualization you can turn on the camera poses to see if they look correct.
