### ISSUE TITLE
Which solution is used for getting cameras.xml from DJI drone?

### ISSUE THREAD

**Issue by PyojinKim** [nickponline/dd-nerf-dataset#3]
Hi,

First of all, I really appreciate for sharing your valuable and meaningful datasets.

I saw and read in the previous issue that the 6-DoF camera poses were calculated using DroneDeploy.
What exact solution and product is used to generate "cameras.xml" file from DJI flying drone?
I'd like to generate "cameras.xml" file with my DJI drone using DroneDeploy, and evaluate NeRF results.

Also, I hope the interesting datasets such as ruins and towers to be released soon! :)

Thanks,
Pyojin Kim.

**Comment by nickponline** [comment]
Signup for DroneDeploy and upload your images. When it has finished
processing I can help you get the cameras.xml.

**Comment by PyojinKim** [comment]
Hi Nicholas,

Thank you very much for your fast and kind words. :)
Could I ask a few more questions about the info. in "cameras.xml" file?

**(1)**
What a 4x4 row-major matrix containing [R t] means in "cameras.xml" file?
I thought it would be T_gc (translation vector denotes the camera position w.r.t. the global frame.)
But in dd2ngp.py, the inverse matrix of this transform matrix in xml is mainly processed...??
https://github.com/nickponline/dd-nerf-dataset/blob/0f60369c9449f3b7f8555a065f979608b1fd23c0/tools/dd2ngp.py#L66

Does a 4x4 row-major matrix in xml files indicates T_gc? or T_cg?

**(2)**
When we upload some images from a drone in DroneDeploy, it shows pretty good (estimated) camera poses and point clouds.
I didn't upload scale info, GNSS, and even K matrix at all, it performs SfM with amazing accuracy and precision!
How the scale value is determined only with the monocular image sequences?
Could you let me know some tutorial (technical) docs how to perform SfM in DroneDeploy?

Thanks,
Pyojin Kim.

**Comment by jmk7791** [comment]
> oneDeploy and upload your images. When it has finished processing I can help you get the cameras.xml.

Hi, I upload my images in my DroneDeploy dashboard. How can I get the cameras.xml file?

**Comment by nickponline** [comment]
@PyojinKim 
1. The transform in `cameras.xml` is world to camera. You can see an example of using it here: https://github.com/nickponline/camera-utils The inverse is use to get the camera pose from the extrinsics like this: https://ksimek.github.io/2012/08/22/extrinsic/

2. The way DroneDeploy performs SfM and MVS is quite in-depth but the GPS data from the EXIF is used to reconstruct the scale of the scene in the absence of GCPS.

@jmk7791  Can you send me the DroneDeploy link and I can help you get the `cameras.xml`.
