### ISSUE TITLE
dronedeploy image uploading error

### ISSUE THREAD

**Issue by jmk7791** [nickponline/dd-nerf-dataset#4]
Hi, thanks for sharing your datasets. I have few questions.
1. I would like to get "camera.xml" file from DJI drone. I upload the images in Dronedeploy. Which extract item should I choose to get "camera.xml" file?
2. I tried to get point cloud from mil19 dataset.(https://github.com/cmusatyalab/mega-nerf) When I upload the images, it said "0 images with valid geographical metadata found. A minimum of 10 images is required." How can I solve this problem?
3. I would like to buy dronedeploy service for academic reasons. Is there any discount information?
Thanks.

**Comment by nickponline** [comment]
1. The `camera.xml` is generate by DroneDeploy not the DJI drone. Can you send me a the DroneDeploy link and I'll help you get the the `camera.xml` file.
2. The images need to have GPS EXIF data to work with DroneDeploy. All images captured from a DJI drone will work, but you must upload more than 10. 
3. Yes there is: https://www.dronedeploy.com/solutions/education/

**Comment by jmk7791** [comment]
Thanks for your answer.
https://www.dronedeploy.com/app2/sites/62dfab4e5dccdaf5b69fb596/maps/62dfa9bd5dccdaf5b69fb595
Here is my project link. I don't know if this is the right link. Please tell me if you need other link.

**Comment by nickponline** [comment]
@jmk7791 Here you go: https://www.dropbox.com/s/lhv0iqj8k5fhgfk/example.zip?dl=0

**Comment by jmk7791** [comment]
Can't I make the example.xml file by myself? Is there any source code to make it?

**Comment by nickponline** [comment]
@jmk7791 You can just need to format the JSON returned from: 

https://www.dronedeploy.com/api/v1/camfile/62dfa9bd5dccdaf5b69fb595

Into XML.
