### ISSUE TITLE
Generate camera.xml file

### ISSUE THREAD

**Issue by hyunJIN7** [nickponline/dd-nerf-dataset#5]
Hi, I really appreciate for sharing your valuable and meaningful datasets.

I would like to get `camera.xml` file for the three projects below.  
I can't generate the `camera.xml` in DronDeploy app, could you make it for me?
- [project 1](https://www.dronedeploy.com/app2/sites/6302f64b1ee6a706258a370e/maps/6302f6e70d348868b89e57a2)
- [project 2](https://www.dronedeploy.com/app2/sites/6303084d157089556ef47637/maps/6303092272783ac02582d4bc)
- [project 3](https://www.dronedeploy.com/app2/sites/6303084d157089556ef47637/maps/630311a6dff8f2ae0ee5c233)

**Comment by nickponline** [comment]
Here you go @hyunJIN7 

https://www.dropbox.com/s/wie08yy1qv942ft/project1.zip?dl=0
https://www.dropbox.com/s/i5zx2dswznc8n11/project2.zip?dl=0
https://www.dropbox.com/s/9pwfzgwam0c353e/project3.zip?dl=0

**Comment by hyunJIN7** [comment]
Thanks for your answer.
